// Catálogo acadêmico de alimentos (macros aproximados por 100g).
// Objetivo: variedade para o algoritmo genético + suporte a vegan/vegetarian/onívoro.

export const foodsCatalog = [
  // ===== PROTEÍNAS (animal) =====
  {
    name: "Peito de frango grelhado",
    category: "protein",
    caloriesKcal: 165,
    proteinG: 31,
    carbsG: 0,
    fatG: 3.6,
    costPer100g: 3.2,
    unit: "g",
    defaultQty: 120,
    tags: "animal,meat,gluten_free,lactose_free",
  },
  {
    name: "Carne bovina magra (patinho)",
    category: "protein",
    caloriesKcal: 170,
    proteinG: 26,
    carbsG: 0,
    fatG: 7,
    costPer100g: 5.5,
    unit: "g",
    defaultQty: 130,
    tags: "animal,meat,gluten_free,lactose_free",
  },
  {
    name: "Lombo suíno grelhado",
    category: "protein",
    caloriesKcal: 190,
    proteinG: 27,
    carbsG: 0,
    fatG: 8,
    costPer100g: 4.7,
    unit: "g",
    defaultQty: 130,
    tags: "animal,meat,gluten_free,lactose_free",
  },
  {
    name: "Sardinha",
    category: "protein",
    caloriesKcal: 208,
    proteinG: 25,
    carbsG: 0,
    fatG: 11,
    costPer100g: 4.2,
    unit: "g",
    defaultQty: 120,
    tags: "animal,fish,gluten_free,lactose_free",
  },
  {
    name: "Atum em água",
    category: "protein",
    caloriesKcal: 116,
    proteinG: 26,
    carbsG: 0,
    fatG: 0.8,
    costPer100g: 6.0,
    unit: "g",
    defaultQty: 120,
    tags: "animal,fish,gluten_free,lactose_free",
  },
  {
    name: "Salmão",
    category: "protein",
    caloriesKcal: 208,
    proteinG: 20,
    carbsG: 0,
    fatG: 13,
    costPer100g: 8.9,
    unit: "g",
    defaultQty: 140,
    tags: "animal,fish,gluten_free,lactose_free",
  },
  {
    name: "Ovo cozido",
    category: "protein",
    caloriesKcal: 155,
    proteinG: 13,
    carbsG: 1.1,
    fatG: 11,
    costPer100g: 2.4,
    unit: "g",
    defaultQty: 100,
    tags: "animal,egg,vegetarian,gluten_free,lactose_free",
  },

  // ===== PROTEÍNAS (vegetarian/vegan) =====
  {
    name: "Tofu",
    category: "protein",
    caloriesKcal: 144,
    proteinG: 15.7,
    carbsG: 3.9,
    fatG: 8.7,
    costPer100g: 4.0,
    unit: "g",
    defaultQty: 130,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Tempeh",
    category: "protein",
    caloriesKcal: 193,
    proteinG: 20,
    carbsG: 9,
    fatG: 11,
    costPer100g: 6.8,
    unit: "g",
    defaultQty: 120,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Grão-de-bico cozido",
    category: "protein",
    caloriesKcal: 164,
    proteinG: 9,
    carbsG: 27,
    fatG: 2.6,
    costPer100g: 1.1,
    unit: "g",
    defaultQty: 160,
    tags: "vegetarian,vegan,gluten_free,lactose_free,legume",
  },
  {
    name: "Lentilha cozida",
    category: "protein",
    caloriesKcal: 116,
    proteinG: 9,
    carbsG: 20,
    fatG: 0.4,
    costPer100g: 1.0,
    unit: "g",
    defaultQty: 170,
    tags: "vegetarian,vegan,gluten_free,lactose_free,legume",
  },
  {
    name: "Feijão cozido",
    category: "protein",
    caloriesKcal: 127,
    proteinG: 8.7,
    carbsG: 22.8,
    fatG: 0.5,
    costPer100g: 0.9,
    unit: "g",
    defaultQty: 170,
    tags: "vegetarian,vegan,gluten_free,lactose_free,legume",
  },
  {
    name: "Ervilha cozida",
    category: "protein",
    caloriesKcal: 84,
    proteinG: 5.4,
    carbsG: 15,
    fatG: 0.4,
    costPer100g: 1.2,
    unit: "g",
    defaultQty: 160,
    tags: "vegetarian,vegan,gluten_free,lactose_free,legume",
  },
  {
    name: "Proteína de soja texturizada (PTS)",
    category: "protein",
    caloriesKcal: 336,
    proteinG: 50,
    carbsG: 30,
    fatG: 1,
    costPer100g: 2.2,
    unit: "g",
    defaultQty: 60,
    tags: "vegetarian,vegan,lactose_free,contains_gluten",
  },

  // ===== CARBOS =====
  {
    name: "Arroz integral cozido",
    category: "carb",
    caloriesKcal: 124,
    proteinG: 2.6,
    carbsG: 25.8,
    fatG: 1.0,
    costPer100g: 0.6,
    unit: "g",
    defaultQty: 160,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Arroz branco cozido",
    category: "carb",
    caloriesKcal: 130,
    proteinG: 2.4,
    carbsG: 28.2,
    fatG: 0.3,
    costPer100g: 0.5,
    unit: "g",
    defaultQty: 170,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Quinoa cozida",
    category: "carb",
    caloriesKcal: 120,
    proteinG: 4.4,
    carbsG: 21.3,
    fatG: 1.9,
    costPer100g: 2.0,
    unit: "g",
    defaultQty: 160,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Macarrão (cozido)",
    category: "carb",
    caloriesKcal: 131,
    proteinG: 5,
    carbsG: 25,
    fatG: 1.1,
    costPer100g: 0.7,
    unit: "g",
    defaultQty: 180,
    tags: "contains_gluten,vegetarian,vegan,lactose_free",
  },
  {
    name: "Aveia",
    category: "carb",
    caloriesKcal: 389,
    proteinG: 16.9,
    carbsG: 66.3,
    fatG: 6.9,
    costPer100g: 1.1,
    unit: "g",
    defaultQty: 55,
    tags: "vegetarian,vegan,lactose_free",
  },
  {
    name: "Pão integral",
    category: "carb",
    caloriesKcal: 247,
    proteinG: 13,
    carbsG: 41,
    fatG: 4.2,
    costPer100g: 1.6,
    unit: "g",
    defaultQty: 70,
    tags: "contains_gluten,vegetarian,vegan,lactose_free",
  },
  {
    name: "Batata doce cozida",
    category: "carb",
    caloriesKcal: 86,
    proteinG: 1.6,
    carbsG: 20.1,
    fatG: 0.1,
    costPer100g: 0.9,
    unit: "g",
    defaultQty: 200,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Batata inglesa cozida",
    category: "carb",
    caloriesKcal: 87,
    proteinG: 1.9,
    carbsG: 20.1,
    fatG: 0.1,
    costPer100g: 0.7,
    unit: "g",
    defaultQty: 200,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Mandioca cozida",
    category: "carb",
    caloriesKcal: 125,
    proteinG: 1.0,
    carbsG: 30,
    fatG: 0.3,
    costPer100g: 0.9,
    unit: "g",
    defaultQty: 190,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Cuscuz de milho",
    category: "carb",
    caloriesKcal: 112,
    proteinG: 2.2,
    carbsG: 23.4,
    fatG: 0.6,
    costPer100g: 0.8,
    unit: "g",
    defaultQty: 180,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },

  // ===== GORDURAS =====
  {
    name: "Azeite de oliva",
    category: "fat",
    caloriesKcal: 884,
    proteinG: 0,
    carbsG: 0,
    fatG: 100,
    costPer100g: 5.5,
    unit: "g",
    defaultQty: 10,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Abacate",
    category: "fat",
    caloriesKcal: 160,
    proteinG: 2,
    carbsG: 8.5,
    fatG: 14.7,
    costPer100g: 2.2,
    unit: "g",
    defaultQty: 90,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Pasta de amendoim",
    category: "fat",
    caloriesKcal: 588,
    proteinG: 25,
    carbsG: 20,
    fatG: 50,
    costPer100g: 3.9,
    unit: "g",
    defaultQty: 20,
    tags: "vegetarian,vegan,gluten_free,lactose_free,nuts",
  },
  {
    name: "Castanha de caju",
    category: "fat",
    caloriesKcal: 553,
    proteinG: 18,
    carbsG: 30,
    fatG: 44,
    costPer100g: 7.0,
    unit: "g",
    defaultQty: 25,
    tags: "vegetarian,vegan,gluten_free,lactose_free,nuts",
  },
  {
    name: "Amêndoas",
    category: "fat",
    caloriesKcal: 579,
    proteinG: 21,
    carbsG: 22,
    fatG: 50,
    costPer100g: 8.2,
    unit: "g",
    defaultQty: 25,
    tags: "vegetarian,vegan,gluten_free,lactose_free,nuts",
  },
  {
    name: "Sementes de chia",
    category: "fat",
    caloriesKcal: 486,
    proteinG: 17,
    carbsG: 42,
    fatG: 31,
    costPer100g: 6.0,
    unit: "g",
    defaultQty: 12,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Sementes de linhaça",
    category: "fat",
    caloriesKcal: 534,
    proteinG: 18,
    carbsG: 29,
    fatG: 42,
    costPer100g: 3.6,
    unit: "g",
    defaultQty: 12,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },

  // ===== VEGETAIS =====
  { name: "Brócolis", category: "veg", caloriesKcal: 34, proteinG: 2.8, carbsG: 6.6, fatG: 0.4, costPer100g: 1.3, unit: "g", defaultQty: 150, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Couve-flor", category: "veg", caloriesKcal: 25, proteinG: 1.9, carbsG: 5, fatG: 0.3, costPer100g: 1.2, unit: "g", defaultQty: 150, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Abobrinha", category: "veg", caloriesKcal: 17, proteinG: 1.2, carbsG: 3.1, fatG: 0.3, costPer100g: 0.9, unit: "g", defaultQty: 180, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Cenoura", category: "veg", caloriesKcal: 41, proteinG: 0.9, carbsG: 10, fatG: 0.2, costPer100g: 0.8, unit: "g", defaultQty: 120, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Espinafre", category: "veg", caloriesKcal: 23, proteinG: 2.9, carbsG: 3.6, fatG: 0.4, costPer100g: 1.5, unit: "g", defaultQty: 120, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Salada (alface e tomate)", category: "veg", caloriesKcal: 18, proteinG: 1.2, carbsG: 3.8, fatG: 0.2, costPer100g: 1.0, unit: "g", defaultQty: 180, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Tomate", category: "veg", caloriesKcal: 18, proteinG: 0.9, carbsG: 3.9, fatG: 0.2, costPer100g: 0.9, unit: "g", defaultQty: 150, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Pepino", category: "veg", caloriesKcal: 15, proteinG: 0.7, carbsG: 3.6, fatG: 0.1, costPer100g: 0.7, unit: "g", defaultQty: 160, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Cebola", category: "veg", caloriesKcal: 40, proteinG: 1.1, carbsG: 9.3, fatG: 0.1, costPer100g: 0.6, unit: "g", defaultQty: 80, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Pimentão", category: "veg", caloriesKcal: 31, proteinG: 1.0, carbsG: 6.0, fatG: 0.3, costPer100g: 1.2, unit: "g", defaultQty: 120, tags: "vegetarian,vegan,gluten_free,lactose_free" },

  // ===== FRUTAS =====
  { name: "Banana", category: "fruit", caloriesKcal: 89, proteinG: 1.1, carbsG: 22.8, fatG: 0.3, costPer100g: 0.9, unit: "g", defaultQty: 120, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Maçã", category: "fruit", caloriesKcal: 52, proteinG: 0.3, carbsG: 13.8, fatG: 0.2, costPer100g: 1.2, unit: "g", defaultQty: 160, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Laranja", category: "fruit", caloriesKcal: 47, proteinG: 0.9, carbsG: 12, fatG: 0.1, costPer100g: 0.8, unit: "g", defaultQty: 180, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Mamão", category: "fruit", caloriesKcal: 43, proteinG: 0.5, carbsG: 11, fatG: 0.3, costPer100g: 1.1, unit: "g", defaultQty: 180, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Manga", category: "fruit", caloriesKcal: 60, proteinG: 0.8, carbsG: 15, fatG: 0.4, costPer100g: 1.3, unit: "g", defaultQty: 160, tags: "vegetarian,vegan,gluten_free,lactose_free" },
  { name: "Morango", category: "fruit", caloriesKcal: 32, proteinG: 0.7, carbsG: 7.7, fatG: 0.3, costPer100g: 2.2, unit: "g", defaultQty: 140, tags: "vegetarian,vegan,gluten_free,lactose_free" },

  // ===== LATICÍNIOS (vegetarian) =====
  {
    name: "Iogurte natural",
    category: "dairy",
    caloriesKcal: 61,
    proteinG: 3.5,
    carbsG: 4.7,
    fatG: 3.3,
    costPer100g: 1.7,
    unit: "g",
    defaultQty: 170,
    tags: "animal,dairy,vegetarian,contains_lactose,gluten_free",
  },
  {
    name: "Queijo branco",
    category: "dairy",
    caloriesKcal: 264,
    proteinG: 18,
    carbsG: 3,
    fatG: 21,
    costPer100g: 4.8,
    unit: "g",
    defaultQty: 60,
    tags: "animal,dairy,vegetarian,contains_lactose,gluten_free",
  },
  {
    name: "Leite desnatado",
    category: "dairy",
    caloriesKcal: 35,
    proteinG: 3.4,
    carbsG: 5,
    fatG: 0.1,
    costPer100g: 0.8,
    unit: "ml",
    defaultQty: 200,
    tags: "animal,dairy,vegetarian,contains_lactose,gluten_free",
  },
  // ===== “LATICÍNIOS” VEGETAIS (vegano) =====
  {
    name: "Bebida de soja",
    category: "dairy",
    caloriesKcal: 45,
    proteinG: 3.2,
    carbsG: 2.0,
    fatG: 2.2,
    costPer100g: 1.3,
    unit: "ml",
    defaultQty: 200,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Bebida de aveia",
    category: "dairy",
    caloriesKcal: 47,
    proteinG: 1.0,
    carbsG: 8.0,
    fatG: 1.5,
    costPer100g: 1.4,
    unit: "ml",
    defaultQty: 200,
    tags: "vegetarian,vegan,lactose_free",
  },
  // ===== PROTEÍNAS ADICIONAIS =====
  {
    name: "Tilápia grelhada",
    category: "protein",
    caloriesKcal: 128,
    proteinG: 26.0,
    carbsG: 0,
    fatG: 3.0,
    costPer100g: 4.1,
    unit: "g",
    defaultQty: 130,
    tags: "animal,fish,gluten_free,lactose_free",
  },
  {
    name: "Camarão cozido",
    category: "protein",
    caloriesKcal: 99,
    proteinG: 24.0,
    carbsG: 0.3,
    fatG: 0.3,
    costPer100g: 10.0,
    unit: "g",
    defaultQty: 100,
    tags: "animal,fish,gluten_free,lactose_free",
  },
  {
    name: "Ervilha (proteína vegetal)",
    category: "protein",
    caloriesKcal: 118,
    proteinG: 7.9,
    carbsG: 21.0,
    fatG: 0.6,
    costPer100g: 1.6,
    unit: "g",
    defaultQty: 180,
    tags: "vegetarian,vegan,gluten_free,lactose_free,legume",
  },
  {
    name: "Edamame (grão de soja jovem)",
    category: "protein",
    caloriesKcal: 122,
    proteinG: 11.0,
    carbsG: 8.9,
    fatG: 5.2,
    costPer100g: 2.7,
    unit: "g",
    defaultQty: 160,
    tags: "vegetarian,vegan,lactose_free,gluten_free",
  },

  // ===== CARBOS ADICIONAIS =====
  {
    name: "Cuscuz marroquino (quinoa/cuscuz)",
    category: "carb",
    caloriesKcal: 120,
    proteinG: 4.4,
    carbsG: 22.0,
    fatG: 1.9,
    costPer100g: 1.8,
    unit: "g",
    defaultQty: 160,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Tapioca",
    category: "carb",
    caloriesKcal: 340,
    proteinG: 0.2,
    carbsG: 84,
    fatG: 0.1,
    costPer100g: 1.1,
    unit: "g",
    defaultQty: 50,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Batata ralada (cozida)",
    category: "carb",
    caloriesKcal: 87,
    proteinG: 1.8,
    carbsG: 20.0,
    fatG: 0.1,
    costPer100g: 0.7,
    unit: "g",
    defaultQty: 220,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },

  // ===== GORDURAS ADICIONAIS =====
  {
    name: "Castanha-do-pará",
    category: "fat",
    caloriesKcal: 656,
    proteinG: 14,
    carbsG: 5,
    fatG: 61,
    costPer100g: 8.5,
    unit: "g",
    defaultQty: 25,
    tags: "vegetarian,vegan,gluten_free,lactose_free,nuts",
  },
  {
    name: "Gergelim (torrado)",
    category: "fat",
    caloriesKcal: 573,
    proteinG: 17,
    carbsG: 23,
    fatG: 50,
    costPer100g: 3.6,
    unit: "g",
    defaultQty: 18,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Chocolate 70% (sem lactose)",
    category: "fat",
    caloriesKcal: 598,
    proteinG: 8,
    carbsG: 40,
    fatG: 45,
    costPer100g: 7.2,
    unit: "g",
    defaultQty: 20,
    tags: "vegetarian,gluten_free,lactose_free",
  },

  // ===== VEGETAIS ADICIONAIS =====
  {
    name: "Berinjela",
    category: "veg",
    caloriesKcal: 25,
    proteinG: 1.0,
    carbsG: 5.9,
    fatG: 0.2,
    costPer100g: 1.1,
    unit: "g",
    defaultQty: 200,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Vagem",
    category: "veg",
    caloriesKcal: 31,
    proteinG: 1.8,
    carbsG: 6.0,
    fatG: 0.2,
    costPer100g: 1.3,
    unit: "g",
    defaultQty: 180,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Repolho roxo",
    category: "veg",
    caloriesKcal: 25,
    proteinG: 1.2,
    carbsG: 5.8,
    fatG: 0.2,
    costPer100g: 0.9,
    unit: "g",
    defaultQty: 220,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },

  // ===== FRUTAS ADICIONAIS =====
  {
    name: "Kiwi",
    category: "fruit",
    caloriesKcal: 61,
    proteinG: 1.1,
    carbsG: 14.7,
    fatG: 0.5,
    costPer100g: 1.8,
    unit: "g",
    defaultQty: 180,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Uva",
    category: "fruit",
    caloriesKcal: 69,
    proteinG: 0.7,
    carbsG: 18.1,
    fatG: 0.2,
    costPer100g: 1.5,
    unit: "g",
    defaultQty: 160,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },

  // ===== FRUTAS (mais variedades) =====
  {
    name: "Pera",
    category: "fruit",
    caloriesKcal: 57,
    proteinG: 0.4,
    carbsG: 15.2,
    fatG: 0.1,
    costPer100g: 1.3,
    unit: "g",
    defaultQty: 160,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Pêssego",
    category: "fruit",
    caloriesKcal: 39,
    proteinG: 0.9,
    carbsG: 9.5,
    fatG: 0.3,
    costPer100g: 1.8,
    unit: "g",
    defaultQty: 160,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Ameixa",
    category: "fruit",
    caloriesKcal: 46,
    proteinG: 0.7,
    carbsG: 11.4,
    fatG: 0.3,
    costPer100g: 1.9,
    unit: "g",
    defaultQty: 140,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Tangerina",
    category: "fruit",
    caloriesKcal: 53,
    proteinG: 0.8,
    carbsG: 13.3,
    fatG: 0.2,
    costPer100g: 1.1,
    unit: "g",
    defaultQty: 180,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Abacaxi",
    category: "fruit",
    caloriesKcal: 50,
    proteinG: 0.5,
    carbsG: 13.1,
    fatG: 0.1,
    costPer100g: 1.7,
    unit: "g",
    defaultQty: 170,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Goiaba",
    category: "fruit",
    caloriesKcal: 68,
    proteinG: 2.6,
    carbsG: 14.3,
    fatG: 1.0,
    costPer100g: 1.6,
    unit: "g",
    defaultQty: 150,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Acerola",
    category: "fruit",
    caloriesKcal: 32,
    proteinG: 0.9,
    carbsG: 7.5,
    fatG: 0.3,
    costPer100g: 2.5,
    unit: "g",
    defaultQty: 120,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Maracujá",
    category: "fruit",
    caloriesKcal: 97,
    proteinG: 2.2,
    carbsG: 23.4,
    fatG: 0.7,
    costPer100g: 1.8,
    unit: "g",
    defaultQty: 140,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Romã",
    category: "fruit",
    caloriesKcal: 83,
    proteinG: 1.7,
    carbsG: 19.0,
    fatG: 1.2,
    costPer100g: 2.2,
    unit: "g",
    defaultQty: 140,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Limão",
    category: "fruit",
    caloriesKcal: 29,
    proteinG: 1.1,
    carbsG: 9.3,
    fatG: 0.3,
    costPer100g: 0.9,
    unit: "g",
    defaultQty: 140,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Lima",
    category: "fruit",
    caloriesKcal: 30,
    proteinG: 0.7,
    carbsG: 10.5,
    fatG: 0.2,
    costPer100g: 0.95,
    unit: "g",
    defaultQty: 140,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Melancia",
    category: "fruit",
    caloriesKcal: 30,
    proteinG: 0.6,
    carbsG: 7.6,
    fatG: 0.2,
    costPer100g: 0.7,
    unit: "g",
    defaultQty: 220,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Melão",
    category: "fruit",
    caloriesKcal: 34,
    proteinG: 0.8,
    carbsG: 8.2,
    fatG: 0.2,
    costPer100g: 0.8,
    unit: "g",
    defaultQty: 200,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Morango (berries extra)",
    category: "fruit",
    caloriesKcal: 32,
    proteinG: 0.7,
    carbsG: 7.7,
    fatG: 0.3,
    costPer100g: 2.2,
    unit: "g",
    defaultQty: 140,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Mirtilo (blueberry)",
    category: "fruit",
    caloriesKcal: 57,
    proteinG: 0.7,
    carbsG: 14.5,
    fatG: 0.3,
    costPer100g: 4.5,
    unit: "g",
    defaultQty: 100,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Framboesa",
    category: "fruit",
    caloriesKcal: 52,
    proteinG: 1.2,
    carbsG: 11.9,
    fatG: 0.7,
    costPer100g: 4.2,
    unit: "g",
    defaultQty: 100,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Amora",
    category: "fruit",
    caloriesKcal: 43,
    proteinG: 1.4,
    carbsG: 9.2,
    fatG: 0.3,
    costPer100g: 4.0,
    unit: "g",
    defaultQty: 100,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Cranberry",
    category: "fruit",
    caloriesKcal: 46,
    proteinG: 0.4,
    carbsG: 11.1,
    fatG: 0.1,
    costPer100g: 3.8,
    unit: "g",
    defaultQty: 100,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Figo",
    category: "fruit",
    caloriesKcal: 74,
    proteinG: 0.3,
    carbsG: 19.4,
    fatG: 0.2,
    costPer100g: 2.0,
    unit: "g",
    defaultQty: 120,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },
  {
    name: "Damasco",
    category: "fruit",
    caloriesKcal: 48,
    proteinG: 1.4,
    carbsG: 11.1,
    fatG: 0.4,
    costPer100g: 2.3,
    unit: "g",
    defaultQty: 120,
    tags: "vegetarian,vegan,gluten_free,lactose_free",
  },

  // ===== LATICÍNIOS ADICIONAIS =====
  {
    name: "Iogurte grego (natural)",
    category: "dairy",
    caloriesKcal: 73,
    proteinG: 9.0,
    carbsG: 4.0,
    fatG: 0.5,
    costPer100g: 1.9,
    unit: "g",
    defaultQty: 170,
    tags: "animal,dairy,contains_lactose,gluten_free,vegetarian",
  },
  {
    name: "Queijo cottage",
    category: "dairy",
    caloriesKcal: 98,
    proteinG: 11.0,
    carbsG: 3.0,
    fatG: 4.3,
    costPer100g: 3.0,
    unit: "g",
    defaultQty: 120,
    tags: "animal,dairy,contains_lactose,gluten_free,vegetarian",
  },
];

